env:
    KT_LINK: "https://github.com/Marvel-land/MK-4.9-WIP"
    KT_BRANCH: "holland-test-1"
    TG_TOKEN: "ENCRYPTED[3c532740ad076565affa0d55bb47c6393e6a7a6ee424c8461e93d0b2e27cfad404b29cbe45ecb18f57c555e07d598d01]"
    TG_CHAT_ID: "ENCRYPTED[1d1c39e15f9e861133c3a424d8d9066a77332d2943cf78581237edd51b05db496cd87e4eea1f6c5e00d21e27177d4d5d]"
    TZ: "Asia/Kolkata"

task:
  name: "Kernel-Builder"
  timeout_in: 480m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 16G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - DEBIAN_FRONTEND=noninteractive
       - mkdir -p /tmp/ccache
       - cd /tmp

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h

  Build_script:
      - bash kernel.sh
