env:
    KT_LINK: "https://github.com/Aflaungos/android_kernel_samsung_m23xq-F"
    KT_BRANCH: "main"
    TG_TOKEN: "ENCRYPTED[3c532740ad076565affa0d55bb47c6393e6a7a6ee424c8461e93d0b2e27cfad404b29cbe45ecb18f57c555e07d598d01]"
    TG_CHAT_ID: "ENCRYPTED[c65f8eba12b8dc6de21248d207cc27feb0ced3fe8455a9a227142867b2ed9972442fde6ac2216d4dcd95a4ac1b5679c6]"
    TZ: "Asia/Kolkata"

task:
  name: "Kernel-Builder"
  timeout_in: 999999m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - DEBIAN_FRONTEND=noninteractive
       - mkdir -p /tmp/ccache
       - cd /tmp

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h

  Build_script:
      - bash kernel.sh
